### ISSUE TITLE
fix 'no starting balance'

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#13]
## Current behavior

-A 'no starting balance' error appears on the _Money on hand/Balance summary screen_ when a user checks 'none and unchecks 'none' on the _Money on hand/Main screen_ and then checks other options.

## Expected behavior

-There should be no text at all on the _Money on hand/Balance summary screen_ if the 'none' on the _Money on hand/Main screen_ is not checked.

![Screen Shot 2020-04-30 at 6 43 23 PM](https://user-images.githubusercontent.com/34319929/80766108-9b560700-8b12-11ea-9bb1-64f9ad7782cc.png)

**Comment by mgreen-simplethread** [comment]
I don't think this issue is described correctly. The thing that happen to Shubhi was that she had checked "None," then gone back and unchecked it, then checked other funding sources and filled in balances for them. When she got to the summary page, it listed those balances _plus_ "No starting balance". 

I fixed this issue by resetting the wizard state whenever the user goes to the start page, and again once a starting balance has been populated (after the final Next button on summary page).

**Comment by MissyM2** [comment]
Ok, yes, you are correct and I tested this.  I think I wrote that after you had actually fixed it just to have a record!
