### ISSUE TITLE
Fix requests when they are offline to prevent dead links

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#21]
Short description explaining the high-level reason for the new issue.

## Current behavior
1.  A user navigates to a Strategies page that includes a link to an external resource.
2. The user is not connected to the internet.
3.  The user receives a dead link.

## Expected behavior
- Under circumstances 1 and 2, the user will be returned to the home page of the app

![]<img src="https://user-images.githubusercontent.com/34319929/80764064-e02b6f00-8b0d-11ea-8a78-fbc4757ec799.png" height="500">

**Comment by mgreen-simplethread** [comment]
This should be fixed. Stage deploy is in progress. You may need to refresh the page a couple of times in order to install and activate the latest service worker.

**Comment by MissyM2** [comment]
@mgreen-simplethread I just tried this on my mobile and got the same response. 
<img src="https://user-images.githubusercontent.com/34319929/81204481-3f1e3780-8f97-11ea-8d66-2f710d571c83.jpg" height="250">

**Comment by mgreen-simplethread** [comment]
Sorry Missy, I was solving a totally different problem related to offline
capability and didn't read the steps to reproduce on this one.

While I can make the app do this, it's not good usability. What it should
do is open external links in new browser tabs and let the browser tell the
user they're offline. Otherwise we are providing a confusing experience
that doesn't work like any other app.

**Comment by MissyM2** [comment]
We will do further investigation to see what should be done.  This is OK for usability testing.
