### ISSUE TITLE
Unexpected behavior on changing Rent expense in Android phone

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#49]
The _Starting Balance_ transaction is a special type of transaction.  A user should only be able to change the amount, not the date, the description or the frequency.

**please note that I have not tried this myself.  These are notes/screenshots from the usability testing.  

fyi @shubhi-raft,@omnipresent07 @RedNumberIX  @jbevis 

## Current behavior
This behavior was discovered in usability testing, round 1 when the participant was using an Android mobile phone.

1. The 'Fix-It Strategy' button appeared when the user's weekly balance was negative
2. The user tapped on the button and the _Fix It Strategy screen_ appeared.
3. The user tapped on the CTA button, suggested in the strategy, to divide their rent into 2 payments.
4. The _transaction input/edit screen_ appeared and the user changed the amount from $800.00 to $400.00 and tapped _Save_. 
5.  The user received the following error  "total must be greater than $0.00".

## Expected behavior
- The user should be able to save the transaction properly and, in testing with simulated Android phone using Developer Tools in Chrome as well as actual iOS phones, the user does not receive an error.

## Screenshots

<img width="205" alt="Screen Shot 2020-06-07 at 11 59 57 PM" src="https://user-images.githubusercontent.com/34319929/83991574-2cdb4480-a91b-11ea-9ba6-eb3ecde961fc.png">
<img width="207" alt="Screen Shot 2020-06-08 at 12 00 28 AM" src="https://user-images.githubusercontent.com/34319929/83991576-2d73db00-a91b-11ea-932d-43468030d1d3.png">
<img width="210" alt="Screen Shot 2020-06-08 at 12 00 43 AM" src="https://user-images.githubusercontent.com/34319929/83991577-2d73db00-a91b-11ea-936e-3e9fa2c450bb.png">
<img width="207" alt="Screen Shot 2020-06-08 at 12 00 56 AM" src="https://user-images.githubusercontent.com/34319929/83991578-2d73db00-a91b-11ea-9c49-3254bd3724b8.png">

**Comment by jbevis** [comment]
@RedNumberIX and I met and discussed this issue.

He was not able to replicate the bug on his android device, and since this only occurred with 1 person during user testing there could be other factors outside of our control.

As such, and given our time crunch I'm going to close this issue with the knowledge that we may encounter OS specific bugs in the future, but given that we are not delivering what would be considered production level code for our 7/6 deliverable, I think it is more productive to shelve this and revisit if/when if becomes a consistent issue.
