### ISSUE TITLE
Add messaging to motivate users to add transactions.

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#51]
Add messaging in the form of pop up windows, as discussed, to motivate users to add their transactions before they review their calendar.

fyi @shubhi-raft @jbevis @omnipresent07 @RedNumberIX @LesliePerucci @meissadia 

## Current behavior

-  Users were confused about what to do when they arrived at the _Calendar View_ after adding their beginning balance.  In order realize the benefit of the _Calendar View_ users need to enter their basic income and expenses.  There is no mechanism that funnels them into this step.

## Expected behavior

-  Add appropriate messaging so that it is clear to the user that they should add their income and expense transactions before they see their calendar.  

## Screenshots

__Current__
<img width="193" alt="Screen Shot 2020-06-15 at 8 58 38 AM" src="https://user-images.githubusercontent.com/34319929/84660207-8082fa80-aee6-11ea-9a77-a74992d02fd8.png">
<img width="195" alt="Screen Shot 2020-06-15 at 8 58 29 AM" src="https://user-images.githubusercontent.com/34319929/84660208-811b9100-aee6-11ea-9414-43b7333eebb4.png">

__Expected__
<img width="945" alt="popUpDot" src="https://user-images.githubusercontent.com/34319929/84660351-b58f4d00-aee6-11ea-9773-d94a2459ae02.png">
![popUp1](https://user-images.githubusercontent.com/34319929/84660352-b58f4d00-aee6-11ea-9889-43e4c577a806.png)

**Comment by jbevis** [comment]
Still more work to do, but here is screen shot of initial narrative modal
<img width="592" alt="Screen Shot 2020-06-16 at 4 48 13 PM" src="https://user-images.githubusercontent.com/21065244/84835630-3f2b4180-aff1-11ea-8152-a4abe1d4a1e4.png">

**Comment by jbevis** [comment]
Still need to abstract this out into reusable piece and implement on the remaining views.

Also, update the overlay to allow for a highlighted feature.

**Comment by jbevis** [comment]
Latest has been deployed to https://cfgov-refresh-dev.herokuapp.com/mmt-my-money-calendar

Awaiting review.

**Comment by shubhi-raft** [comment]
For 

**3. Fix-It Narrative**  

Issue Description:  Adding narrative to fix-it strategies when in red. [Should this narrative direct users to click the “Fix-It” button or direct them to continue entering expenses before hand?] 

Proposed Logic: Overlay appears (only once) the first time a user arrives at the Fix-It Strategies page. 

Heading: Have you entered all of your income and expenses? 

Body: Fix-It Strategies are tips to help you stay cash positive based upon the transactions you entered into the calendar. So, make sure you’ve entered all income and expenses before exploring the strategies on this page for the most accurate information.  

Button: OK 

Current Behavior
- The pop-up appears on fix-it strategies. 
![Screen Shot 2020-06-29 at 10 22 26 AM](https://user-images.githubusercontent.com/22622384/86018221-07f66080-b9f3-11ea-8f59-2201682d8815.png)

Expected Behavior
- The model should appear on calendar page
![Screen Shot 2020-06-29 at 10 32 19 AM](https://user-images.githubusercontent.com/22622384/86028904-7e4d8f80-ba00-11ea-9724-bf4751fdfa63.png)

**Comment by shubhi-raft** [comment]
For 

**2. Continue Transaction Narrative**

Issue Description: Same issue as previous narrative. 

Proposed Logic: Overlay appears (only once) after the user has successfully entered their first expense/income and returned to the Calendar Summary Screen 

Heading: Congratulations!  

Body: You’ve just entered your first transaction into the calendar. The more transactions you enter the more this tool can help you manage your budget. 

Button: OK 

Current Behavior:
Does not show-up when expense is entered. I tried adding water/sewage without adding income. Message did not showup.

Expected:
Modal pops up after the first transaction is added - either income or expense.

**Comment by jbevis** [comment]
@shubhi-raft 

With regard to the fix-it-strategy modal. The narrative notifications document indicates that the overlay should appear only once upon the user's first visit to the fix-it strategies page. The body content is also relative to the user being on the page. I can change this instead launch on the calendar view, the first time a user goes into the red, but will need to know what the body content should be updated to?

**Comment by jbevis** [comment]
There are also some logistical issues to consider. The fix-it-strategy modal is to appear over the calendar, there is a situation where a user, who enters an expense as their first transaction, thus going into the red immediately, will trigger both the "congratulations" and "fix-it" modal simultaneously. This then places two modals on the same view, which looks odd and we'll need to consider how to handle turning them off subsequently so that both are viewed.

Given the time crunch, I'd like to propose we keep the fix it modal on the first visit to the fix it screen for now. We can always revisit if they decide it has to be on the calendar view. But given that the fix it button is bold and red, I think that is enough of a prompt to click, and then have the modal provide extra context once they arrive at the fix it strategies page.

of course happy to discuss.
